---
- debug: msg="Will use zookeeper id={{ zookeeper.id }}"

- set_fact:
    zoo_keeper_index: "{{zookeeper.id}}"
    
# Update all packages to the latest version
- apt: upgrade=dist

- name: Install OpenJDK
  tags: java
  apt: pkg=openjdk-7-jre-headless update-cache=yes state=latest

- name: Install Zookeeper
  apt: name=zookeeperd state=latest

- stat: path={{zookeeper_conf_dir}}
  register: confdir

- name: Create conf_dir
  file: path={{zookeeper_conf_dir}} state=directory owner=root group=root mode=755
  when: confdir.stat.exists == False

- name: Setup zoo.cfg
  template: dest="{{zookeeper_conf_dir}}/zoo.cfg" src=zoo.cfg.j2
  notify:
    - restart zookeeper
    - wait for zookeeper port

- name: Setup myid
  template: dest="{{zookeeper_conf_dir}}/myid" src=myid.j2
  notify:
    - restart zookeeper
    - wait for zookeeper port

- name: Setup environment
  template: dest="{{zookeeper_conf_dir}}/environment" src=environment.j2
  notify:
    - restart zookeeper
    - wait for zookeeper port

- name: Create log_dir
  file: path={{zookeeper_log_dir}} state=directory owner=zookeeper group=zookeeper mode=755

- name: Setup log4j
  copy: dest="{{zookeeper_conf_dir}}/log4j.properties" owner=root group=root mode=644 src=log4j.properties
  notify:
    - restart zookeeper
    - wait for zookeeper port
